- name: add ceph stable repository
  apt_repository:
    repo: "deb http://download.ceph.com/debian-luminous {{ debian_version }} main"
    state: present
- name: install ceph-common
  apt:
    name: ceph-common
    state: present
- name: write ceph.conf
  template:
    src: ceph.conf.j2
    dest: /etc/ceph/ceph.conf
