- name: "Build hosts file"
  blockinfile:
      dest: /etc/hosts
      block: |
        {% for hostname in groups['friendship_express'] %}
        {% if hostvars[hostname].fe_addr is defined %}
        {{ hostvars[hostname].fe_addr }} {{hostname}}
        {% endif %}
        {% endfor %}
      state: present
