- name: create auth token
  command: ceph auth get-or-create {{ceph_client_name}}
  delegate_to: "{{groups['mons'][0]}}"
  register: ceph_client_keyring
- name: give capabilities
  command: ceph auth caps {{ceph_client_name}} {{ceph_client_caps}}
  delegate_to: "{{groups['mons'][0]}}"
  when: ceph_client_caps is defined
- name: write auth keyring
  copy:
    dest: /etc/ceph/ceph.{{ceph_client_name}}.keyring
    content: "{{ceph_client_keyring['stdout']}}\n"

